"""Core data models and image analysis primitives for Visual Continuity Lab."""

from .analyzer import Analyzer, AnalyzerConfig, ContinuityAnalyzer, analyze_sequence, compare_features, extract_features
from .image_metrics import (
    color_distribution,
    compare_feature_matches,
    feature_matching,
    contrast,
    edge_map,
    histogram,
    optical_flow,
    perceptual_hash,
    perceptual_hash_distance,
)
from .models import (
    ContinuityReport,
    DriftDimension,
    DriftResult,
    Drift,
    CharacterRegion,
    Frame,
    FrameFeatures,
    FrameRecord,
    HealthScores,
    Issue,
    ROI,
    Sequence,
)
from .sequence import (
    FrameSequence,
    SUPPORTED_IMAGE_EXTENSIONS,
    load_image,
    sequence_from_folder,
    sequence_from_image,
    sequence_from_paths,
    sequence_from_source,
    sequence_from_shot,
    sequence_from_video,
)
from .io import (
    APPLICATION_VERSION,
    FRAMEFORGE_SCHEMA_VERSION,
    export_frameforge,
    export_frameforge_json,
    export_json,
    import_frameforge,
    import_json,
    report_from_frameforge,
    sequence_from_frameforge,
)

__all__ = [
    "ContinuityAnalyzer",
    "Analyzer",
    "AnalyzerConfig",
    "analyze_sequence",
    "compare_features",
    "extract_features",
    "ContinuityReport",
    "DriftDimension",
    "DriftResult",
    "Drift",
    "Frame",
    "CharacterRegion",
    "FrameFeatures",
    "FrameRecord",
    "HealthScores",
    "Issue",
    "ROI",
    "Sequence",
    "FrameSequence",
    "SUPPORTED_IMAGE_EXTENSIONS",
    "load_image",
    "sequence_from_folder",
    "sequence_from_image",
    "sequence_from_paths",
    "sequence_from_source",
    "sequence_from_shot",
    "sequence_from_video",
    "APPLICATION_VERSION",
    "FRAMEFORGE_SCHEMA_VERSION",
    "export_frameforge",
    "export_frameforge_json",
    "export_json",
    "import_frameforge",
    "import_json",
    "report_from_frameforge",
    "sequence_from_frameforge",
    "histogram",
    "contrast",
    "color_distribution",
    "perceptual_hash",
    "perceptual_hash_distance",
    "edge_map",
    "compare_feature_matches",
    "feature_matching",
    "optical_flow",
]
