"""Serializable models used by the continuity engine.

The models are deliberately plain dataclasses.  They are useful to a UI, but
also make the import/export contract stable for other tools.  Every model has
``to_dict``/``from_dict`` methods and therefore round-trips through JSON
without requiring custom encoders in the caller.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, ClassVar, Mapping
import json


def _json_value(value: Any) -> Any:
    """Convert common scientific Python values into JSON-compatible values."""

    # Keep numpy optional.  Importing it here must never be required merely to
    # read a report generated by another machine.
    if hasattr(value, "tolist"):
        try:
            return value.tolist()
        except Exception:
            pass
    if isinstance(value, Path):
        return str(value)
    if isinstance(value, Mapping):
        return {str(k): _json_value(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_value(v) for v in value]
    return value


@dataclass
class ROI:
    """A character region of interest.

    Coordinates are normalized to ``0..1`` by default, so an ROI survives a
    change in source image resolution.  Pixel coordinates can be used by
    passing ``normalized=False``.  ``locked`` records the user's intent and is
    honored by callers that update automatic ROI estimates.
    """

    x: float
    y: float
    width: float
    height: float
    normalized: bool = True
    locked: bool = False
    label: str = "character"

    def clamp(self) -> "ROI":
        x, y = max(0.0, float(self.x)), max(0.0, float(self.y))
        w, h = max(0.0, float(self.width)), max(0.0, float(self.height))
        if self.normalized:
            x = min(1.0, x)
            y = min(1.0, y)
            w = min(w, max(0.0, 1.0 - x))
            h = min(h, max(0.0, 1.0 - y))
        return ROI(x, y, w, h, self.normalized, self.locked, self.label)

    def as_pixels(self, image_size: tuple[int, int]) -> tuple[int, int, int, int]:
        """Return ``(left, top, right, bottom)`` for ``(width, height)``."""

        width, height = max(1, int(image_size[0])), max(1, int(image_size[1]))
        roi = self.clamp()
        if roi.normalized:
            left, top = roi.x * width, roi.y * height
            right, bottom = (roi.x + roi.width) * width, (roi.y + roi.height) * height
        else:
            left, top = roi.x, roi.y
            right, bottom = roi.x + roi.width, roi.y + roi.height
        # Keep at least one pixel while remaining inside image bounds, even
        # for a degenerate ROI pinned at the right/bottom edge.
        left = max(0, min(max(0, width - 1), int(round(left))))
        top = max(0, min(max(0, height - 1), int(round(top))))
        right = max(left + 1, min(width, int(round(right))))
        bottom = max(top + 1, min(height, int(round(bottom))))
        return left, top, right, bottom

    @classmethod
    def from_dict(cls, data: Mapping[str, Any] | None) -> "ROI | None":
        if not data:
            return None
        # A manifest may use ``roi`` as a container of named pixel boxes
        # (``character``, ``face``, ``hair``...) rather than one normalized ROI.
        # Do not silently turn that container into a 0x0 crop.
        if not any(key in data for key in ("x", "y", "width", "height", "w", "h")):
            return None
        return cls(
            float(data.get("x", 0.0)),
            float(data.get("y", 0.0)),
            float(data.get("width", data.get("w", 0.0))),
            float(data.get("height", data.get("h", 0.0))),
            bool(data.get("normalized", True)),
            bool(data.get("locked", False)),
            str(data.get("label", "character")),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "x": self.x,
            "y": self.y,
            "width": self.width,
            "height": self.height,
            "normalized": self.normalized,
            "locked": self.locked,
            "label": self.label,
        }


@dataclass
class FrameRecord:
    """Metadata for one still image or extracted video frame."""

    frame_id: str
    path: str | None = None
    frame_number: int = 0
    timestamp: float | None = None
    character: str | None = None
    shot: str | None = None
    status: str = "unanalysed"
    roi: ROI | None = None
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def id(self) -> str:
        """Convenience alias used by integrations."""

        return self.frame_id

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "FrameRecord":
        raw_path = data.get("path") or data.get("file")
        return cls(
            frame_id=str(data.get("frame_id", data.get("frameId", data.get("id", "")))),
            path=str(raw_path) if raw_path is not None else None,
            frame_number=int(data.get("frame_number", data.get("frameNumber", data.get("frame", 0))) or 0),
            timestamp=(float(data["timestamp"]) if data.get("timestamp") is not None else None),
            character=(str(data["character"]) if data.get("character") is not None else None),
            shot=(str(data["shot"]) if data.get("shot") is not None else None),
            status=str(data.get("status", "unanalysed")),
            roi=(data.get("roi") if isinstance(data.get("roi"), ROI) else ROI.from_dict(data.get("roi"))),
            metadata={**dict(data.get("metadata", {})),
                      **({"roi_boxes": data.get("roi")} if isinstance(data.get("roi"), Mapping) and data.get("roi") and ROI.from_dict(data.get("roi")) is None else {})},
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "frame_id": self.frame_id,
            "path": self.path,
            "frame_number": self.frame_number,
            "timestamp": self.timestamp,
            "character": self.character,
            "shot": self.shot,
            "status": self.status,
            "roi": self.roi.to_dict() if self.roi else None,
            "metadata": _json_value(self.metadata),
        }


@dataclass
class Sequence:
    """An ordered image sequence and its analysis metadata."""

    sequence_id: str
    frames: list[FrameRecord] = field(default_factory=list)
    master_reference: str | None = None
    shot: str | None = None
    character: str | None = None
    status: str = "unanalysed"
    manual_labels: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def id(self) -> str:
        return self.sequence_id

    def __len__(self) -> int:
        return len(self.frames)

    def __iter__(self):
        return iter(self.frames)

    @classmethod
    def from_paths(cls, paths, **kwargs):
        """Convenience constructor delegated to the input adapter."""
        from .sequence import sequence_from_paths
        return sequence_from_paths(paths, **kwargs)

    @classmethod
    def from_folder(cls, folder, **kwargs):
        from .sequence import sequence_from_folder
        return sequence_from_folder(folder, **kwargs)

    @classmethod
    def from_video(cls, video, **kwargs):
        from .sequence import sequence_from_video
        return sequence_from_video(video, **kwargs)

    @classmethod
    def from_source(cls, source, **kwargs):
        from .sequence import sequence_from_source
        return sequence_from_source(source, **kwargs)

    @classmethod
    def from_shot(cls, shot, **kwargs):
        from .sequence import sequence_from_shot
        return sequence_from_shot(shot, **kwargs)

    def frame(self, frame_id: str) -> FrameRecord:
        for frame in self.frames:
            if frame.frame_id == frame_id:
                return frame
        raise KeyError(f"Unknown frame_id: {frame_id}")

    def set_roi(self, roi: ROI, frame_id: str | None = None, lock: bool | None = None) -> None:
        """Set an ROI on one frame, or all frames when ``frame_id`` is omitted."""
        if not isinstance(roi, ROI):
            roi = ROI(*roi, normalized=True)
        value = ROI(roi.x, roi.y, roi.width, roi.height, roi.normalized,
                    roi.locked if lock is None else lock, roi.label).clamp()
        if frame_id is None:
            for frame in self.frames:
                frame.roi = ROI(value.x, value.y, value.width, value.height,
                                value.normalized, value.locked, value.label)
        else:
            self.frame(frame_id).roi = value

    def add_label(self, frame_id: str, label: str, note: str = "") -> dict[str, Any]:
        allowed = {"Good", "Bad Face", "Bad Hair", "Bad Costume", "Bad Pose", "Bad Background"}
        if label not in allowed:
            raise ValueError(f"Unsupported label {label!r}; choose one of {sorted(allowed)}")
        entry = {"frame_id": frame_id, "label": label, "note": note}
        self.manual_labels.append(entry)
        return entry

    def set_master_reference(self, frame: str | int | FrameRecord) -> str:
        if isinstance(frame, FrameRecord):
            frame_id = frame.frame_id
        elif isinstance(frame, int):
            frame_id = self.frames[frame].frame_id
        else:
            frame_id = str(frame)
            self.frame(frame_id)  # validate early
        self.master_reference = frame_id
        return frame_id

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "Sequence":
        # Accept both our schema and the compact FrameForge interchange shape.
        frames_data = data.get("frames", data.get("sequence", []))
        if isinstance(frames_data, Mapping):
            frames_data = list(frames_data.values())
        frames = [f if isinstance(f, FrameRecord) else FrameRecord.from_dict(f) for f in frames_data]
        manifest_w, manifest_h = float(data.get("width", 0) or 0), float(data.get("height", 0) or 0)
        if manifest_w > 0 and manifest_h > 0:
            for frame in frames:
                boxes = frame.metadata.get("roi_boxes") if isinstance(frame.metadata, dict) else None
                bbox = boxes.get("character") if isinstance(boxes, Mapping) else None
                if frame.roi is None and isinstance(bbox, (list, tuple)) and len(bbox) == 4:
                    x1, y1, x2, y2 = (float(v) for v in bbox)
                    frame.roi = ROI(x1 / manifest_w, y1 / manifest_h,
                                    max(1.0, x2 - x1) / manifest_w,
                                    max(1.0, y2 - y1) / manifest_h,
                                    True, True, "manifest-character").clamp()
        return cls(
            sequence_id=str(data.get("sequence_id", data.get("sequenceId", data.get("id", "sequence")))),
            frames=frames,
            master_reference=(str(data.get("master_reference", data.get("masterReferenceFrameId"))) if data.get("master_reference", data.get("masterReferenceFrameId")) is not None else None),
            shot=(str(data.get("shot", data.get("shotId"))) if data.get("shot", data.get("shotId")) is not None else None),
            character=(str(data["character"]) if data.get("character") is not None else None),
            status=str(data.get("status", "unanalysed")),
            manual_labels=list(data.get("manual_labels", data.get("labels", [])) or []),
            metadata=dict(data.get("metadata", {})),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "sequence_id": self.sequence_id,
            "frames": [f.to_dict() for f in self.frames],
            "master_reference": self.master_reference,
            "shot": self.shot,
            "character": self.character,
            "status": self.status,
            "manual_labels": _json_value(self.manual_labels),
            "metadata": _json_value(self.metadata),
        }

    def to_json(self, *, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=indent)

    @classmethod
    def from_json(cls, payload: str | bytes | Path) -> "Sequence":
        if isinstance(payload, Path):
            payload = payload.read_text(encoding="utf-8")
        return cls.from_dict(json.loads(payload))


@dataclass
class FrameFeatures:
    """Numerical features extracted from a frame.

    Arrays are kept as lists in the model so reports stay JSON serializable.
    ``extra`` is an extension point for future detectors (face landmarks,
    segmentation, etc.) without changing the interchange schema.
    """

    image_size: tuple[int, int] = (0, 0)
    brightness: float = 0.0
    contrast: float = 0.0
    histogram: list[float] = field(default_factory=list)
    color_distribution: list[float] = field(default_factory=list)
    perceptual_hash: str = ""
    edge_density: float = 0.0
    edge_signature: list[float] = field(default_factory=list)
    sharpness: float = 0.0
    character_position: tuple[float, float] = (0.5, 0.5)
    character_scale: float = 1.0
    body_aspect: float = 1.0
    face_signature: list[float] = field(default_factory=list)
    hair_signature: list[float] = field(default_factory=list)
    hair_color: tuple[float, float, float] = (0.0, 0.0, 0.0)
    costume_color: tuple[float, float, float] = (0.0, 0.0, 0.0)
    background_histogram: list[float] = field(default_factory=list)
    roi: ROI | None = None
    extra: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return _json_value({
            "image_size": self.image_size,
            "brightness": self.brightness,
            "contrast": self.contrast,
            "histogram": self.histogram,
            "color_distribution": self.color_distribution,
            "perceptual_hash": self.perceptual_hash,
            "edge_density": self.edge_density,
            "edge_signature": self.edge_signature,
            "sharpness": self.sharpness,
            "character_position": self.character_position,
            "character_scale": self.character_scale,
            "body_aspect": self.body_aspect,
            "face_signature": self.face_signature,
            "hair_signature": self.hair_signature,
            "hair_color": self.hair_color,
            "costume_color": self.costume_color,
            "background_histogram": self.background_histogram,
            "roi": self.roi.to_dict() if self.roi else None,
            "extra": self.extra,
        })

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "FrameFeatures":
        return cls(
            image_size=tuple(data.get("image_size", (0, 0))),
            brightness=float(data.get("brightness", 0.0)),
            contrast=float(data.get("contrast", 0.0)),
            histogram=list(data.get("histogram", [])),
            color_distribution=list(data.get("color_distribution", [])),
            perceptual_hash=str(data.get("perceptual_hash", "")),
            edge_density=float(data.get("edge_density", 0.0)),
            edge_signature=list(data.get("edge_signature", [])),
            sharpness=float(data.get("sharpness", 0.0)),
            character_position=tuple(data.get("character_position", (0.5, 0.5))),
            character_scale=float(data.get("character_scale", 1.0)),
            body_aspect=float(data.get("body_aspect", 1.0)),
            face_signature=list(data.get("face_signature", [])),
            hair_signature=list(data.get("hair_signature", [])),
            hair_color=tuple(data.get("hair_color", (0.0, 0.0, 0.0))),
            costume_color=tuple(data.get("costume_color", (0.0, 0.0, 0.0))),
            background_histogram=list(data.get("background_histogram", [])),
            roi=ROI.from_dict(data.get("roi")),
            extra=dict(data.get("extra", {})),
        )


@dataclass
class DriftDimension:
    name: str
    score: float
    severity: str
    delta: float | None = None
    evidence: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return _json_value({
            "name": self.name,
            "score": self.score,
            "severity": self.severity,
            "delta": self.delta,
            "evidence": self.evidence,
        })

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "DriftDimension":
        return cls(str(data.get("name", "")), float(data.get("score", 0.0)),
                   str(data.get("severity", "low")),
                   float(data["delta"]) if data.get("delta") is not None else None,
                   dict(data.get("evidence", {})))


@dataclass
class DriftResult:
    from_frame: str
    to_frame: str
    dimensions: dict[str, DriftDimension] = field(default_factory=dict)
    overall_score: float = 0.0
    severity: str = "low"
    evidence: dict[str, Any] = field(default_factory=dict)
    comparison: str = "adjacent"

    @property
    def frame_from(self) -> str:
        return self.from_frame

    @property
    def frame_to(self) -> str:
        return self.to_frame

    def to_dict(self) -> dict[str, Any]:
        return _json_value({
            "from_frame": self.from_frame,
            "to_frame": self.to_frame,
            "dimensions": {k: v.to_dict() for k, v in self.dimensions.items()},
            "overall_score": self.overall_score,
            "severity": self.severity,
            "evidence": self.evidence,
            "comparison": self.comparison,
        })

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "DriftResult":
        dimensions = {k: DriftDimension.from_dict(v) for k, v in dict(data.get("dimensions", {})).items()}
        return cls(str(data.get("from_frame", data.get("frame_from", ""))),
                   str(data.get("to_frame", data.get("frame_to", ""))), dimensions,
                   float(data.get("overall_score", 0.0)), str(data.get("severity", "low")),
                   dict(data.get("evidence", {})), str(data.get("comparison", "adjacent")))


@dataclass
class Issue:
    issue_id: str
    type: str
    start_frame: str
    end_frame: str
    severity: str
    evidence: dict[str, Any] = field(default_factory=dict)
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return _json_value(self.__dict__)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "Issue":
        return cls(str(data.get("issue_id", data.get("id", ""))), str(data.get("type", "")),
                   str(data.get("start_frame", "")), str(data.get("end_frame", "")),
                   str(data.get("severity", "low")), dict(data.get("evidence", {})),
                   str(data.get("notes", "")))


@dataclass
class HealthScores:
    identity_stability: float = 100.0
    motion_stability: float = 100.0
    color_stability: float = 100.0
    lighting_stability: float = 100.0
    background_stability: float = 100.0
    overall: float = 100.0
    sample_count: int = 0

    @property
    def identity(self) -> float:
        return self.identity_stability

    @property
    def motion(self) -> float:
        return self.motion_stability

    @property
    def color(self) -> float:
        return self.color_stability

    @property
    def lighting(self) -> float:
        return self.lighting_stability

    @property
    def background(self) -> float:
        return self.background_stability

    def to_dict(self) -> dict[str, Any]:
        return _json_value(self.__dict__)

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "HealthScores":
        return cls(*(float(data.get(k, 100.0)) for k in (
            "identity_stability", "motion_stability", "color_stability",
            "lighting_stability", "background_stability", "overall")),
            int(data.get("sample_count", 0)))


@dataclass
class ContinuityReport:
    sequence_id: str
    adjacent_results: list[DriftResult] = field(default_factory=list)
    master_results: list[DriftResult] = field(default_factory=list)
    issues: list[Issue] = field(default_factory=list)
    timeline: dict[str, list[dict[str, Any]]] = field(default_factory=dict)
    health: HealthScores = field(default_factory=HealthScores)
    bad_frames: list[str] = field(default_factory=list)
    recommended_frames: list[str] = field(default_factory=list)
    manual_labels: list[dict[str, Any]] = field(default_factory=list)
    frame_features: dict[str, FrameFeatures] = field(default_factory=dict)
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: dict[str, Any] = field(default_factory=dict)

    # Compact aliases help consumers that use the names from the product brief.
    @property
    def drift_timeline(self) -> dict[str, list[dict[str, Any]]]:
        return self.timeline

    @property
    def drift(self) -> list[DriftResult]:
        """Compatibility alias for adjacent comparisons."""
        return self.adjacent_results

    @property
    def master_drift(self) -> list[DriftResult]:
        return self.master_results

    @property
    def sequence_health(self) -> HealthScores:
        return self.health

    def to_dict(self, include_features: bool = True) -> dict[str, Any]:
        payload = {
            "sequence_id": self.sequence_id,
            "adjacent_results": [r.to_dict() for r in self.adjacent_results],
            "master_results": [r.to_dict() for r in self.master_results],
            "issues": [i.to_dict() for i in self.issues],
            "timeline": _json_value(self.timeline),
            "health": self.health.to_dict(),
            "bad_frames": self.bad_frames,
            "recommended_frames": self.recommended_frames,
            "manual_labels": _json_value(self.manual_labels),
            "generated_at": self.generated_at,
            "metadata": _json_value(self.metadata),
        }
        if include_features:
            payload["frame_features"] = {k: v.to_dict() for k, v in self.frame_features.items()}
        return payload

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "ContinuityReport":
        return cls(
            sequence_id=str(data.get("sequence_id", data.get("id", "sequence"))),
            adjacent_results=[DriftResult.from_dict(x) for x in data.get("adjacent_results", data.get("drifts", []))],
            master_results=[DriftResult.from_dict(x) for x in data.get("master_results", [])],
            issues=[Issue.from_dict(x) for x in data.get("issues", [])],
            timeline={str(k): list(v) for k, v in dict(data.get("timeline", {})).items()},
            health=HealthScores.from_dict(data.get("health", {})),
            bad_frames=list(data.get("bad_frames", [])),
            recommended_frames=list(data.get("recommended_frames", [])),
            manual_labels=list(data.get("manual_labels", [])),
            frame_features={str(k): FrameFeatures.from_dict(v) for k, v in dict(data.get("frame_features", {})).items()},
            generated_at=str(data.get("generated_at", "")),
            metadata=dict(data.get("metadata", {})),
        )

    def to_json(self, *, indent: int = 2, include_features: bool = True) -> str:
        return json.dumps(self.to_dict(include_features=include_features), ensure_ascii=False, indent=indent)

    @classmethod
    def from_json(cls, payload: str | bytes | Path) -> "ContinuityReport":
        if isinstance(payload, Path):
            payload = payload.read_text(encoding="utf-8")
        return cls.from_dict(json.loads(payload))


# Short aliases make the JSON schema pleasant to use from notebooks while the
# verbose names remain the documented API.
Frame = FrameRecord
CharacterRegion = ROI
Drift = DriftResult
